const data = {
	products: [
		{
			name: "New Shirt",
			slug: "new shirt",
			Category: "Shirt",
			image: "/images/shirt1.jpg",
			price: 10,
			brand: "Nike",
			rating: 4.5,
			numReviews: 8,
			countInStock: 20,
			description: "New fashion Arrival",
		},
		{
			name: "Fit Shirt",
			slug: "fir shirt",
			Category: "Shirts",
			image: "/images/shirt2.jpg",
			price: 15,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 8,
			countInStock: 20,
			description: "A popular shirt",
		},
		{
			name: "Slim Shirt",
			slug: "slim shirt",
			Category: "Shirts",
			image: "/images/shirt3.jpg",
			price: 12,
			brand: "Raymond",
			rating: 4.3,
			numReviews: 3,
			countInStock: 20,
			description: "A popular shirt",
		},
		{
			name: "Golf Pants",
			slug: "golf pants",
			Category: "Pants",
			image: "/images/pants1.jpg",
			price: 35,
			brand: "Oliver",
			rating: 2.9,
			numReviews: 13,
			countInStock: 20,
			description: "Smart looking pants",
		},
		{
			name: "Fit Pants",
			slug: "fit pants",
			Category: "Pants",
			image: "/images/pants2.jpg",
			price: 55,
			brand: "Zara",
			rating: 2.9,
			numReviews: 7,
			countInStock: 20,
			description: "A popular pants",
		},
		{
			name: "Classic Pants",
			slug: "classic pants",
			Category: "Pants",
			image: "/images/pant3.jpg",
			price: 65,
			brand: "Casely",
			rating: 2.4,
			numReviews: 14,
			countInStock: 20,
			description: "A popular pants",
		},
	],
};

export default data;
